---
apiVersion: v1
kind: Service
metadata:
  name: kube-exm-app
spec:
  selector:
    app: kube-exm-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-exm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-exm-app
  template:
    metadata:
      labels:
        app: kube-exm-app
    spec:
      containers:
        - name: kube-exm-app
          image: shvyrev/kube-exm-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: GREETING_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: config-demo-config
                  key: greeting.message
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-demo-config
data:
  greeting.message: "Hello from Kubernetes ConfigMap!"